import { access, writeFile } from "fs/promises";
import { constants } from "fs";
import { basename, extname, join, normalize, resolve } from "path";
import { randomUUID } from "crypto";

function comfyUiModelsDir() {
  return (
    process.env.COMFYUI_MODELS_DIR ??
    join(Buffer.from("Q29tZnlVSQ==", "base64").toString("utf8"), "models")
  );
}

export const LORA_RUNNER_DIR =
  process.env.LORA_RUNNER_DIR ?? join("runners", "sd-scripts");
const isWindows = process.platform === "win32";
const DEFAULT_RUNNER_PYTHON = join(
  LORA_RUNNER_DIR,
  ".venv",
  isWindows ? "Scripts/python.exe" : "bin/python"
);

export const LORA_RUNNER_PYTHON =
  process.env.LORA_RUNNER_PYTHON ?? DEFAULT_RUNNER_PYTHON;
export const SDXL_TRAIN_SCRIPT = join(LORA_RUNNER_DIR, "sdxl_train_network.py");

export function loraOutputDir() {
  return join(comfyUiModelsDir(), "loras");
}

export interface LoraRunnerStatus {
  ready: boolean;
  runnerDir: string;
  pythonPath: string;
  trainScript: string;
  outputDir: string;
  missing: string[];
}

export interface LoraTrainingConfigInput {
  runId: string;
  loraName: string;
  triggerWords: string;
  baseModel: string;
  category: string;
  imageDir: string;
  outputName: string;
}

async function exists(path: string) {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

export async function getLoraRunnerStatus(): Promise<LoraRunnerStatus> {
  const checks = [
    { label: "runners/sd-scripts", path: LORA_RUNNER_DIR },
    { label: "runner Python venv", path: LORA_RUNNER_PYTHON },
    { label: "sdxl_train_network.py", path: SDXL_TRAIN_SCRIPT },
  ];
  const results = await Promise.all(
    checks.map(async (check) => ({
      ...check,
      exists: await exists(check.path),
    }))
  );
  const missing = results
    .filter((result) => !result.exists)
    .map((result) => `${result.label}: ${result.path}`);

  return {
    ready: missing.length === 0,
    runnerDir: LORA_RUNNER_DIR,
    pythonPath: LORA_RUNNER_PYTHON,
    trainScript: SDXL_TRAIN_SCRIPT,
    outputDir: loraOutputDir(),
    missing,
  };
}

export function safeOutputName(value: string) {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/\.[a-z0-9]+$/i, "")
      .replace(/[^a-z0-9가-힣_-]+/gi, "-")
      .replace(/^-+|-+$/g, "") || `lora-${randomUUID().slice(0, 8)}`
  );
}

export function checkpointPath(baseModel: string) {
  const root = resolve(join(comfyUiModelsDir(), "checkpoints"));
  const fullPath = resolve(join(root, baseModel));

  if (fullPath !== root && !fullPath.startsWith(`${root}/`) && !fullPath.startsWith(`${root}\\`)) {
    throw new Error("Invalid base model path");
  }

  return fullPath;
}

export function safeImageExtension(file: File) {
  const fromName = extname(file.name).toLowerCase();
  if ([".png", ".jpg", ".jpeg", ".webp"].includes(fromName)) return fromName;
  if (file.type === "image/png") return ".png";
  if (file.type === "image/webp") return ".webp";
  return ".jpg";
}

function tomlString(value: string) {
  return JSON.stringify(value);
}

export function buildSdxlTrainingConfig({
  loraName,
  triggerWords,
  baseModel,
  category,
  imageDir,
  outputName,
}: LoraTrainingConfigInput) {
  const tokens = triggerWords
    .split(",")
    .map((word) => word.trim())
    .filter(Boolean)
    .join(", ");
  const classToken = category || "character";

  return `# Generated by Image Gen LoRA Training
[general]
shuffle_caption = true
caption_extension = ".txt"
keep_tokens = 1

[[datasets]]
resolution = 1024
batch_size = 1
enable_bucket = true
bucket_no_upscale = true
min_bucket_reso = 512
max_bucket_reso = 1536

  [[datasets.subsets]]
  image_dir = ${tomlString(normalize(imageDir))}
  class_tokens = ${tomlString(`${tokens} ${classToken}`.trim())}
  num_repeats = 10

[metadata]
lora_name = ${tomlString(loraName)}
base_model = ${tomlString(baseModel)}
output_name = ${tomlString(outputName)}
`;
}

export async function writeTrainingReadme(runDir: string, lines: string[]) {
  await writeFile(join(runDir, "README.txt"), `${lines.join("\n")}\n`);
}

export function displayFilename(path: string) {
  return basename(path);
}
