export interface ModelConfig {
  id: string;
  name: string;
  description: string;
  provider: "comfyui";
  supports: {
    lora: boolean;
    embeddings: boolean;
    custom_model: boolean;
    ip_adapter: boolean;
    face_id: boolean;
    negative_prompt: boolean;
  };
  defaults: {
    num_inference_steps: number;
    guidance_scale: number;
  };
}

export const AVAILABLE_MODELS: ModelConfig[] = [
  {
    id: "comfyui/local-sdxl",
    name: "Local ComfyUI",
    description: "Local checkpoint, LoRA, embeddings",
    provider: "comfyui",
    supports: {
      lora: true,
      embeddings: true,
      custom_model: true,
      ip_adapter: false,
      face_id: true,
      negative_prompt: true,
    },
    defaults: { num_inference_steps: 30, guidance_scale: 7.5 },
  },
];

export interface GenerationParams {
  backend: "comfyui" | "a1111" | "forge";
  model: string;
  model_name: string;
  prompt: string;
  negative_prompt: string;
  num_inference_steps: number;
  guidance_scale: number;
  width: number;
  height: number;
  num_images: number;
  output_format: "jpeg" | "png";
  generation_mode: "text_to_image" | "pose_reference" | "image_to_image";
  seed: number | null;
  sampler_name: string;
  scheduler: string;
  clip_skip: number;
  vae_name: string;
  // ComfyUI Krea 2 build variant. "generic" = the app's standard single-pass KSampler
  // recipe; "refined" = generic + a low-denoise 2nd KSampler pass (stock nodes only, no
  // RES4LYF) that cleans up the residual grain turbo checkpoints leave behind;
  // "pornmaster" = faithful RES4LYF 2-stage ClownsharKSampler recipe from the PornMaster
  // Krea2 Turbo workflow. Only consulted for Krea 2 checkpoints on ComfyUI.
  krea2_workflow: "generic" | "refined" | "pornmaster" | "moody";
  // Moody finish only: how much of the photo-upscaler pass is mixed over the plain
  // lanczos enlargement (0 = lanczos only, 1 = upscaler only).
  output_upscale_blend: number;
  upscale_model_name: string;
  hires_upscale: number;
  hires_steps: number;
  hires_denoise: number;
  img2img_resize: number;
  adetailer_enabled: boolean;
  adetailer_model: string;
  adetailer_checkpoint: string;
  adetailer_prompt: string;
  adetailer_negative_prompt: string;
  adetailer_use_steps: boolean;
  adetailer_steps: number;
  adetailer_confidence: number;
  adetailer_mask_blur: number;
  adetailer_noise_multiplier: number;
  adetailer_inpaint_only_masked: boolean;
  adetailer_loras: LoraConfig[];
  adetailer_denoise: number;
  loras: LoraConfig[];
  embeddings: EmbeddingConfig[];
  controlnets: ControlNetConfig[];
  prompt_weighting: boolean;
  style_image: string | null;
  character_image: string | null;
  // PuLID identity weight for character_image. Higher reproduces the reference
  // face more faithfully; lower lets the prompt/pose lead. Only consulted on the
  // SDXL/Illustrious workflow when character_image is set. Sweet spot ~0.7–1.0.
  character_reference_strength: number;
  source_image: string | null;
  denoise_strength: number;
  pose_reference_image: string | null;
  pose_reference_model: string;
  pose_reference_strength: number;
  enable_safety_checker: boolean;
}

export interface LoraConfig {
  path: string;
  scale: number;
}

export interface EmbeddingConfig {
  path: string;
  tokens: string;
}

export interface ControlNetConfig {
  model: string;
  image: string | null;
  strength: number;
  start_percent: number;
  end_percent: number;
}

export interface CivitaiOrigin {
  imageId: number;
  imageUrl: string;
  pageUrl: string;
  username?: string;
}

export interface GeneratedImage {
  id: string;
  url: string;
  thumbnailUrl?: string;
  params: GenerationParams | null;
  timestamp: number;
  filename: string;
  sizeSemantics?: "base" | "final";
  generation?: ImageGenerationStatus;
  civitaiOrigin?: CivitaiOrigin;
  workspaces?: string[];
  // When the image was generated by picking a saved character/situation (from
  // the Paimon picker), these link it back so the character studio and picker
  // can show it as a thumbnail on that situation.
  characterId?: string;
  situationId?: string;
}

// Sentinel filter id for items that belong to no workspace. Not a real
// workspace — used as an activeWorkspaceId value and list query param.
export const UNGROUPED_WORKSPACE_ID = "__ungrouped__";

// Workspaces are one shared set of folders across the whole app; what differs
// per screen is only which media the folder is filtered by. Image generation
// sees its images, video generation its ComfyUI videos, and the SeeDance screen
// its SeeDance clips — the workspace (and its RunPod share) is the same record.
export type WorkspaceMedia = "images" | "videos" | "seedance";

export const WORKSPACE_MEDIA: WorkspaceMedia[] = ["images", "videos", "seedance"];

export function isWorkspaceMedia(value: unknown): value is WorkspaceMedia {
  return (
    value === "images" || value === "videos" || value === "seedance"
  );
}

export interface Workspace {
  id: string;
  name: string;
  createdAt: number;
}

export interface WorkspaceSummary extends Workspace {
  count: number;
}

// A character is a reusable subject: its identity (appearance + wardrobe),
// backgrounds, and situations are authored once here and later composed into an
// image-generation prompt. Every prompt-bearing field is paired with a
// natural-language `description` (what the user wrote / Paimon narrated) and a
// `prompt` (the tag/prompt text actually fed to the model), both editable.
export interface CharacterOutfit {
  id: string;
  name: string;
  description: string;
  prompt: string;
}

export interface CharacterBackground {
  id: string;
  name: string;
  description: string;
  prompt: string;
}

export interface CharacterSituation {
  id: string;
  name: string;
  description: string;
  prompt: string;
  // Which registered outfit/background this situation pairs with. null = 자동
  // (composition falls back to the first entry). Lets a single character have
  // many situations that each pick their own wardrobe and setting.
  outfitId: string | null;
  backgroundId: string | null;
}

// 메인 이미지 — the character's reference image. It doubles as the list
// thumbnail, but its real job is to be the BASELINE every other image of this
// character is generated from: its generation metadata carries the prompt
// format and the model settings a new situation render should keep. Only a
// generated image can be set here — an upload or a clipboard paste has no
// generation metadata, so it could never act as that baseline.
export interface CharacterMainImage {
  // App-served image URL, e.g. "/api/images/<file>".
  url: string;
  // Gallery thumbnail URL for the same file, when known.
  thumbnailUrl?: string;
  filename: string;
  // The image's generation metadata. null only for a legacy record whose
  // sidecar is gone; such a main image still shows, but carries no baseline.
  params: GenerationParams | null;
}

export interface Character {
  id: string;
  name: string;
  // 간단 정보 shown under the name in the list.
  summary: string;
  // 기본정보 — a longer synopsis/story that Paimon can read to generate
  // situations (and choose fitting outfits/backgrounds for each).
  synopsis: string;
  // 메인 이미지 — see CharacterMainImage. null until one is picked.
  mainImage: CharacterMainImage | null;
  // 아이덴티티 — detailed appearance.
  appearanceDescription: string;
  appearancePrompt: string;
  // 아이덴티티 — one or more wardrobes.
  outfits: CharacterOutfit[];
  // 배경 — one or more environments/settings.
  backgrounds: CharacterBackground[];
  // 상황.
  situations: CharacterSituation[];
  // Manual position in the character list (ascending). Legacy records without
  // this fall back to createdAt so their relative order is preserved on read.
  order: number;
  createdAt: number;
  updatedAt: number;
}

// The list view only needs the light fields; the full Character is loaded for
// editing. Kept identical to Character for now (the file store returns whole
// records) but named separately so the list contract can slim down later.
export type CharacterSummary = Character;

export function createEmptyCharacter(name: string): Omit<
  Character,
  "id" | "order" | "createdAt" | "updatedAt"
> {
  return {
    name,
    summary: "",
    synopsis: "",
    mainImage: null,
    appearanceDescription: "",
    appearancePrompt: "",
    outfits: [],
    backgrounds: [],
    situations: [],
  };
}

// Composes a character's identity + a chosen outfit + background + situation
// into a single generation prompt. Missing/empty parts are skipped. Used both
// by the client picker and reported to the image-gen Paimon as a hint.
export function composeCharacterPrompt(
  character: Pick<
    Character,
    "appearancePrompt" | "outfits" | "backgrounds" | "situations"
  >,
  options?: { outfitId?: string; backgroundId?: string; situationId?: string }
): string {
  const situation =
    character.situations.find((item) => item.id === options?.situationId) ??
    character.situations[0];

  // A situation carries its own outfit/background choice; an explicit option
  // overrides it, and both fall back to the first registered entry.
  const outfitId = options?.outfitId ?? situation?.outfitId ?? undefined;
  const outfit =
    character.outfits.find((item) => item.id === outfitId) ??
    character.outfits[0];

  const backgroundId =
    options?.backgroundId ?? situation?.backgroundId ?? undefined;
  const background =
    character.backgrounds.find((item) => item.id === backgroundId) ??
    character.backgrounds[0];

  return [
    character.appearancePrompt,
    outfit?.prompt,
    background?.prompt,
    situation?.prompt,
  ]
    .map((part) => (typeof part === "string" ? part.trim() : ""))
    .filter(Boolean)
    .join(", ");
}

export interface ImageGenerationStatus {
  state: "queued" | "waiting" | "generating" | "completed" | "canceled" | "error";
  progress: number;
  message: string;
}

export type VideoModelPreset = "wan-smoothmix" | "wan-base" | "ltx-10eros";

// Automatic NSFW censoring applied in-graph, just before frames become a video.
// The censor node (ComfyUI-Nudenet `ApplyNudenet`) detects the targeted regions
// per frame and obscures them; `method` picks how (mosaic/blur), `min_score` the
// detection confidence gate, `blocks` the mosaic/blur coarseness, and `targets`
// the NudeNet label ids to censor (defaults to genitalia + anus).
export type CensorMethod = "pixelate" | "blur" | "gaussian_blur";

// NudeNet detection labels. `true` = censor this region, `false` = leave it.
export type CensorLabel =
  | "FEMALE_GENITALIA_EXPOSED"
  | "FEMALE_GENITALIA_COVERED"
  | "MALE_GENITALIA_EXPOSED"
  | "ANUS_EXPOSED"
  | "ANUS_COVERED"
  | "BUTTOCKS_EXPOSED"
  | "FEMALE_BREAST_EXPOSED";

export interface CensorSettings {
  enabled: boolean;
  method: CensorMethod;
  min_score: number;
  blocks: number;
  targets: CensorLabel[];
}

// Genitalia-focused default, matching the user's stated goal ("성기 검열").
export const DEFAULT_CENSOR_TARGETS: CensorLabel[] = [
  "FEMALE_GENITALIA_EXPOSED",
  "FEMALE_GENITALIA_COVERED",
  "MALE_GENITALIA_EXPOSED",
  "ANUS_EXPOSED",
];

export const DEFAULT_CENSOR_SETTINGS: CensorSettings = {
  enabled: false,
  method: "pixelate",
  min_score: 0.25,
  blocks: 8,
  targets: DEFAULT_CENSOR_TARGETS,
};

export interface VideoGenerationParams {
  video_model: VideoModelPreset;
  video_pipeline: string;
  video_pipeline_settings: Record<string, string | number | boolean>;
  prompt: string;
  negative_prompt: string;
  width: number;
  height: number;
  num_frames: number;
  fps: number;
  duration_seconds: number;
  num_inference_steps: number;
  guidance_scale: number;
  vae_tile_size: number;
  vae_tile_overlap: number;
  vae_temporal_size: number;
  vae_temporal_overlap: number;
  smooth_xxx_strength: number;
  mating_press_strength: number;
  lightx2v_high_strength: number;
  lightx2v_low_strength: number;
  ltx_dr34_strength: number;
  ltx_dasiwa_strength: number;
  seed: number | null;
  source_image: string | null;
  enable_sound: boolean;
  sound_prompt: string;
  negative_sound_prompt: string;
  sound_duration_seconds: number;
  censor: CensorSettings;
}

export interface GeneratedAudio {
  id: string;
  url: string;
  params: VideoGenerationParams | null;
  timestamp: number;
  filename: string;
  contentType: string;
}

export interface GeneratedVideo {
  id: string;
  url: string;
  params: VideoGenerationParams | null;
  timestamp: number;
  filename: string;
  contentType: string;
  audios?: GeneratedAudio[];
  // Workspace ids this video belongs to — the same workspaces the image gallery
  // uses, so a folder can hold both images and videos while each screen only
  // shows its own media.
  workspaces?: string[];
  // Present while a video is queued/generating (client-only pending card) and
  // set to a terminal state on error/cancel. Reuses the image status shape.
  generation?: ImageGenerationStatus;
}

export interface GenerationStatus {
  state: "idle" | "uploading" | "generating" | "completed" | "canceled" | "error";
  progress: number;
  message: string;
}

export interface ImportedCivitaiResource {
  type: "checkpoint" | "lora" | "embedding" | "vae" | "upscaler" | "other";
  name: string;
  versionName?: string;
  baseModel?: string;
  thumbnailUrl?: string;
  tags?: string[];
  weight?: number;
  hash?: string;
  fileName?: string;
  modelId?: number;
  modelVersionId?: number;
  url: string;
}

export interface CivitaiLicenseInfo {
  allowNoCredit?: boolean;
  allowCommercialUse?: string[];
  allowDerivatives?: boolean;
  allowDifferentLicense?: boolean;
}

export interface CivitaiImportResult {
  imageId: number;
  imageUrl: string;
  pageUrl: string;
  username?: string;
  importedTags: string[];
  metadataHidden?: boolean;
  warning?: string;
  params: Partial<GenerationParams>;
  resources: ImportedCivitaiResource[];
  metadataReport?: CivitaiMetadataReport;
  recommendations?: CivitaiGenerationRecommendation[];
}

export type CivitaiMetadataStatus =
  | "confirmed"
  | "inferred"
  | "missing"
  | "conflict";

export interface CivitaiMetadataField {
  key: string;
  label: string;
  status: CivitaiMetadataStatus;
  value?: string;
  note?: string;
}

export interface CivitaiMetadataReport {
  reproducibility: "high" | "medium" | "low";
  summary: string;
  confirmedCount: number;
  inferredCount: number;
  missingCount: number;
  fields: CivitaiMetadataField[];
}

export interface CivitaiGenerationRecommendation {
  id: string;
  title: string;
  goal: "closest" | "literal" | "stable" | "quality";
  description: string;
  caution?: string;
  params: Partial<GenerationParams>;
}

export interface HistoryMissingResource extends ImportedCivitaiResource {
  reason: string;
}

export interface HistoryEntry {
  id: string;
  source: "civitai" | "generated";
  createdAt: number;
  requestedUrl: string;
  imageId?: number;
  imageUrl: string;
  localImageUrl: string | null;
  localImageFilename: string | null;
  pageUrl?: string;
  username?: string;
  params: GenerationParams;
  importedParams: Partial<GenerationParams>;
  resources: ImportedCivitaiResource[];
  missingResources: HistoryMissingResource[];
  importedTags: string[];
  userTags: string[];
  rawImport?: CivitaiImportResult;
}

export const DEFAULT_PARAMS: GenerationParams = {
  backend: "comfyui",
  model: "comfyui/local-sdxl",
  model_name: "sd_xl_base_1.0.safetensors",
  prompt: "",
  negative_prompt: "low quality, blurry, deformed, ugly, bad anatomy, bad hands, missing fingers",
  num_inference_steps: 30,
  guidance_scale: 7.5,
  width: 1024,
  height: 1024,
  num_images: 1,
  output_format: "jpeg",
  generation_mode: "text_to_image",
  seed: null,
  sampler_name: "dpmpp_2m",
  scheduler: "karras",
  clip_skip: 1,
  vae_name: "",
  krea2_workflow: "generic",
  output_upscale_blend: 0.6,
  upscale_model_name: "",
  hires_upscale: 1,
  hires_steps: 12,
  hires_denoise: 0.45,
  img2img_resize: 1.5,
  adetailer_enabled: false,
  adetailer_model: "face_yolov8n.pt",
  adetailer_checkpoint: "",
  adetailer_prompt: "",
  adetailer_negative_prompt: "",
  adetailer_use_steps: false,
  adetailer_steps: 20,
  adetailer_confidence: 0.5,
  adetailer_mask_blur: 4,
  adetailer_noise_multiplier: 1,
  adetailer_inpaint_only_masked: true,
  adetailer_loras: [],
  adetailer_denoise: 0.4,
  loras: [],
  embeddings: [],
  controlnets: [],
  prompt_weighting: true,
  style_image: null,
  character_image: null,
  character_reference_strength: 0.7,
  source_image: null,
  denoise_strength: 0.6,
  pose_reference_image: null,
  pose_reference_model: "",
  pose_reference_strength: 0.8,
  enable_safety_checker: false,
};

export const DEFAULT_VIDEO_PARAMS: VideoGenerationParams = {
  video_model: "wan-smoothmix",
  video_pipeline: "sulphur-ltx23-i2v-base-high-quality",
  video_pipeline_settings: {},
  prompt: "",
  negative_prompt: "low quality, blurry, flicker, warped, distorted motion",
  width: 480,
  height: 592,
  num_frames: 81,
  fps: 16,
  duration_seconds: 5,
  num_inference_steps: 6,
  guidance_scale: 1,
  vae_tile_size: 256,
  vae_tile_overlap: 64,
  vae_temporal_size: 64,
  vae_temporal_overlap: 16,
  smooth_xxx_strength: 1,
  mating_press_strength: 0.85,
  lightx2v_high_strength: 3,
  lightx2v_low_strength: 1.5,
  ltx_dr34_strength: 1,
  ltx_dasiwa_strength: 1,
  seed: null,
  source_image: null,
  enable_sound: false,
  sound_prompt: "",
  negative_sound_prompt: "",
  sound_duration_seconds: 6,
  censor: DEFAULT_CENSOR_SETTINGS,
};

export const IMAGE_SIZES = [
  { label: "512×512", width: 512, height: 512 },
  { label: "512×768", width: 512, height: 768 },
  { label: "768×512", width: 768, height: 512 },
  { label: "768×1024", width: 768, height: 1024 },
  { label: "1024×768", width: 1024, height: 768 },
  { label: "1024×1024", width: 1024, height: 1024 },
] as const;

export const IMAGE_SIZE_CONSTRAINTS = {
  min: 256,
  max: 2048,
  step: 8,
} as const;

export function randomGenerationSeed() {
  return Math.floor(Math.random() * Number.MAX_SAFE_INTEGER);
}

export function normalizeGenerationSeed(value: unknown) {
  if (value === null || value === undefined || value === "") {
    return randomGenerationSeed();
  }

  const numericValue = Number(value);

  if (!Number.isFinite(numericValue) || numericValue < 0) {
    return randomGenerationSeed();
  }

  return Math.floor(numericValue);
}

export function normalizeImageDimension(value: unknown) {
  const numericValue = Number(value);

  if (!Number.isFinite(numericValue)) {
    return DEFAULT_PARAMS.width;
  }

  const { min, max, step } = IMAGE_SIZE_CONSTRAINTS;
  const steppedValue = Math.round(numericValue / step) * step;

  return Math.min(Math.max(steppedValue, min), max);
}

export function getModelConfig(modelId: string): ModelConfig {
  return AVAILABLE_MODELS.find((m) => m.id === modelId) ?? AVAILABLE_MODELS[0];
}

export type HiresModelFamily =
  | "flux"
  | "sd3"
  | "pony"
  | "illustrious"
  | "sdxl"
  | "sd15"
  | "unknown";

export interface HiresPreset {
  family: HiresModelFamily;
  familyLabel: string;
  steps: number;
  denoise: number;
}

// hires refine defaults are keyed to the model family: the second pass denoise
// mostly tracks how much detail the base architecture invents, and each family
// has a community-accepted sweet spot for an ESRGAN-style upscaler.
const HIRES_PRESETS: Record<HiresModelFamily, Omit<HiresPreset, "family">> = {
  flux: { familyLabel: "Flux", steps: 10, denoise: 0.35 },
  sd3: { familyLabel: "SD3", steps: 12, denoise: 0.4 },
  pony: { familyLabel: "Pony", steps: 10, denoise: 0.4 },
  illustrious: { familyLabel: "Illustrious / NoobAI", steps: 10, denoise: 0.4 },
  sdxl: { familyLabel: "SDXL", steps: 12, denoise: 0.4 },
  sd15: { familyLabel: "SD 1.5", steps: 12, denoise: 0.5 },
  unknown: { familyLabel: "기본", steps: 12, denoise: 0.45 },
};

export function detectModelFamily(modelName: string): HiresModelFamily {
  const name = modelName.toLowerCase();

  if (/flux/.test(name)) return "flux";
  if (/(^|[^a-z])sd_?3|sd3/.test(name)) return "sd3";
  if (/pony/.test(name)) return "pony";
  if (/illustrious|ilxl|noob|noobai/.test(name)) return "illustrious";
  if (/xl|sdxl|pdxl/.test(name)) return "sdxl";
  if (/sd_?1\.?5|v1-?5|sd15|1_5/.test(name)) return "sd15";

  return "unknown";
}

// Krea 2 and Z-Image checkpoints ship as diffusion-model (unet) files that only
// this app's ComfyUI pipelines can load; the A1111/Forge WebUI backends have no
// workflow for them. The UI pins the backend with this instead of letting a
// stale WebUI selection fail at generation time.
export function requiresComfyUiBackend(modelName: string) {
  const name = modelName ?? "";
  return /krea[-_ ]?2/i.test(name) || /z[-_ ]?image/i.test(name);
}

export function getHiresPreset(modelName: string): HiresPreset {
  const family = detectModelFamily(modelName ?? "");
  return { family, ...HIRES_PRESETS[family] };
}
